### ISSUE TITLE
Reverse AST traversal like Babel's path.exit()

### ISSUE THREAD

**Issue by voidptr9** [swc-project/plugin-strip-console#2]
This should probably be posted on the main repo but figured it would be relevant to plugin authors. Essentially, visiting an AST node would prevent its children from being visited, as in, visiting a `VariableDeclaration` stops its child `Identifier` node from being visited. Is there a switch for enabling this behavior? I recall working with Babel's plugin API that tends to have exactly this via an `exit()` method on nodes.

Currently, this is how the traversal appears:

```ts
class SomeVisitor extends Visitor {
  visitVariableDeclaration(vardecl: VariableDeclaration): VariableDeclaration {
    // Some morphings...
    return vardecl;
  }

  visitIdentifier(ident: Identifier): Identifier {
    console.log("This identifier cannot be accessed as a child of a vardecl.");
    return ident;
  }
}
```

**Comment by kdy1** [comment]
You can do 
```ts
vardecl  = super.visitVariableDeclaration(vardecl)
```

**Comment by voidptr9** [comment]
Exactly! This works as expected. Thanks, closing this issue.
